package com.splitandmerge.mkvslice.ui.help

import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ArrowBack
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.splitandmerge.mkvslice.R

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun HelpScreen(
    onBack: () -> Unit
) {
    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("How to Use & Help", fontWeight = FontWeight.Bold) },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.Default.ArrowBack, contentDescription = "Back")
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = MaterialTheme.colorScheme.surfaceVariant
                )
            )
        }
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .background(MaterialTheme.colorScheme.background)
                .padding(padding)
                .verticalScroll(rememberScrollState())
                .padding(16.dp)
        ) {
            Text(
                text = "Welcome to Video Splitter",
                fontSize = 22.sp,
                fontWeight = FontWeight.Bold,
                color = MaterialTheme.colorScheme.primary,
                modifier = Modifier.padding(bottom = 8.dp)
            )
            Text(
                text = "Learn how to use the key features of the app with step-by-step instructions and visual guides.",
                fontSize = 14.sp,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
                modifier = Modifier.padding(bottom = 24.dp)
            )

            HelpSection(
                title = "1. Library & Home Screen",
                imageRes = R.drawable.s2_library_phone,
                steps = listOf(
                    "Launch the app to see your job execution history.",
                    "Tap on the floating action buttons to start a new Split, Merge, Set Default Tracks, or Rename Videos flow.",
                    "View real-time progress for active operations or tap on completed entries to view split/merge result details."
                )
            )

            HelpSection(
                title = "2. Splitting Video Files",
                imageRes = R.drawable.s5_split_config_phone,
                steps = listOf(
                    "Choose a video file via the system file picker.",
                    "Configure size limit caps (in GB) or specify part quantities to split by.",
                    "Preview segment locations, check keep-screen-on state, and execute the in-place split operation."
                )
            )

            HelpSection(
                title = "3. Merging Video Parts",
                imageRes = R.drawable.s10_merge_order,
                steps = listOf(
                    "Select multiple part files that you wish to concatenate.",
                    "Drag and drop to adjust the chronological order of the parts.",
                    "Verify segment continuity and kick off the merge process (no re-encoding, extremely fast)."
                )
            )

            HelpSection(
                title = "4. Setting Default Tracks",
                imageRes = R.drawable.s12_set_default_tracks_list,
                steps = listOf(
                    "Pick a single MKV file or scan an entire folder recursively.",
                    "Tap on a file row to open the track editor and select your preferred audio/subtitle default track numbers.",
                    "Use 'Apply to all similar files' to auto-configure language-matched tracks across the batch."
                )
            )

            HelpSection(
                title = "5. Batch Rename Videos (Title-Clean)",
                imageRes = R.drawable.s14_rename_preview,
                steps = listOf(
                    "Pick video files or choose a directory to scan recursively.",
                    "Clean titles automatically: preview 'before' and 'after' names generated by regex patterns.",
                    "Toggle checkbox selection, resolve naming collisions, and click 'Rename' to save changes in place."
                )
            )

            HelpSection(
                title = "6. Naming Cleanup Patterns",
                imageRes = R.drawable.s15a_cleanup_patterns_phone,
                steps = listOf(
                    "Go to Settings -> Title Cleanup Patterns.",
                    "Define custom Regex rules and optional 'Replace-with' targets.",
                    "Test pattern effects instantly on a dummy name text input before saving your changes."
                )
            )

            Spacer(modifier = Modifier.height(24.dp))
        }
    }
}

@Composable
fun HelpSection(
    title: String,
    imageRes: Int,
    steps: List<String>
) {
    Card(
        modifier = Modifier
            .fillMaxWidth()
            .padding(vertical = 12.dp),
        colors = CardDefaults.cardColors(
            containerColor = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.4f)
        ),
        shape = RoundedCornerShape(16.dp)
    ) {
        Column(modifier = Modifier.padding(16.dp)) {
            Text(
                text = title,
                fontSize = 18.sp,
                fontWeight = FontWeight.Bold,
                color = MaterialTheme.colorScheme.primary,
                modifier = Modifier.padding(bottom = 12.dp)
            )

            Image(
                painter = painterResource(id = imageRes),
                contentDescription = title,
                modifier = Modifier
                    .fillMaxWidth()
                    .height(320.dp)
                    .clip(RoundedCornerShape(8.dp))
                    .background(MaterialTheme.colorScheme.surfaceVariant),
                contentScale = ContentScale.Fit
            )

            Spacer(modifier = Modifier.height(16.dp))

            steps.forEachIndexed { index, step ->
                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(vertical = 4.dp),
                    verticalAlignment = Alignment.Top
                ) {
                    Text(
                        text = "${index + 1}. ",
                        fontSize = 14.sp,
                        fontWeight = FontWeight.Bold,
                        color = MaterialTheme.colorScheme.primary
                    )
                    Text(
                        text = step,
                        fontSize = 14.sp,
                        color = MaterialTheme.colorScheme.onSurface,
                        lineHeight = 20.sp
                    )
                }
            }
        }
    }
}
