package com.splitandmerge.mkvslice.theme

import androidx.compose.ui.graphics.Color

// Light mode color tokens derived from Deep Teal #006B5F seed
val LightPrimary = Color(0xFF006B5F)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFF95E8D9)
val LightOnPrimaryContainer = Color(0xFF00201C)
val LightSecondary = Color(0xFF65558F)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFE8DEFF)
val LightOnSecondaryContainer = Color(0xFF20005F)
val LightTertiary = Color(0xFFA43E20)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFFDBD0)
val LightOnTertiaryContainer = Color(0xFF3D0700)
val LightBackground = Color(0xFFFAFDFF)
val LightOnBackground = Color(0xFF191C1B)
val LightSurface = Color(0xFFFAFDFF)
val LightOnSurface = Color(0xFF191C1B)
val LightSurfaceVariant = Color(0xFFDAE5E1)
val LightOnSurfaceVariant = Color(0xFF3F4946)
val LightOutline = Color(0xFF6F7977)
val LightOutlineVariant = Color(0xFFDEE5E3)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)

// Dark (AMOLED) mode color tokens derived from Deep Teal #006B5F seed
val DarkPrimary = Color(0xFF83D5C6)
val DarkOnPrimary = Color(0xFF003731)
val DarkPrimaryContainer = Color(0xFF006B5F)
val DarkOnPrimaryContainer = Color(0xFF95E8D9)
val DarkSecondary = Color(0xFFCDBDFF)
val DarkOnSecondary = Color(0xFF370492)
val DarkSecondaryContainer = Color(0xFF4E2CA9)
val DarkOnSecondaryContainer = Color(0xFFBDA8FF)
val DarkTertiary = Color(0xFFFFB59E)
val DarkOnTertiary = Color(0xFF55200D)
val DarkTertiaryContainer = Color(0xFF8F4C36)
val DarkOnTertiaryContainer = Color(0xFFFFCEBF)
val DarkBackground = Color(0xFF000000)
val DarkOnBackground = Color(0xFFE0E3E1)
val DarkSurface = Color(0xFF000000)
val DarkOnSurface = Color(0xFFE0E3E1)
val DarkSurfaceVariant = Color(0xFF313634)
val DarkOnSurfaceVariant = Color(0xFFBEC9C5)
val DarkOutline = Color(0xFF889390)
val DarkOutlineVariant = Color(0xFF3E4946)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
